# -*- coding: utf-8 -*-

locations = ["kuzey", "doğu", "batı", "güney", "kuzeybatı", "kuzeydoğu", "güneybatı", "güneydoğu", "anadolu"]



cities = ['Adana', 'Adıyaman', 'Afyon', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin',
			'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale',
			'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
			'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'Mersin', 'İstanbul', 'İzmir',
			'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya',
			'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya',
			'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak',
			'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak',
			'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce', "Ayvalık",
            "Cunda"]

countries = [ 'Türkiye', 'ABD Virgin Adaları', 'Afganistan', 'Aland Adaları', 'Almanya', 'Amerika Birleşik Devletleri',
			  'ABD',
			  'Amerika Birleşik Devletleri Küçük Dış Adaları', 'Amerikan Samoası', 'Andora', 'Angola', 'Anguilla',
			  'Antarktika', 'Antigua ve Barbuda', 'Arjantin', 'Arnavutluk', 'Aruba', 'Avrupa Birliği', 'Avustralya',
			  'Avusturya', 'Azerbaycan', 'Bahamalar', 'Bahreyn', 'Bangladeş', 'Barbados', 'Batı Sahara', 'Belize',
			  'Belçika', 'Benin', 'Bermuda', 'Beyaz Rusya', 'Bhutan', 'Bilinmeyen veya Geçersiz Bölge',
			  'Birleşik Arap Emirlikleri', 'Birleşik Krallık', 'Bolivya', 'Bosna Hersek', 'Botsvana', 'Bouvet Adası',
			  'Brezilya', 'Brunei', 'Bulgaristan', 'Burkina Faso', 'Burundi', 'Cape Verde', 'Cebelitarık', 'Cezayir',
			  'Christmas Adası', 'Cibuti', 'Cocos Adaları', 'Cook Adaları', 'Çad', 'Çek Cumhuriyeti', 'Çin',
			  'Danimarka', 'Dominik', 'Dominik Cumhuriyeti', 'Doğu Timor', 'Ekvator', 'Ekvator Ginesi', 'El Salvador',
			  'Endonezya', 'Eritre', 'Ermenistan', 'Estonya', 'Etiyopya', 'Falkland Adaları (Malvinalar)',
			  'Faroe Adaları', 'Fas', 'Fiji', 'Fildişi Sahilleri', 'Filipinler', 'Filistin Bölgesi', 'Finlandiya',
			  'Fransa', 'Fransız Guyanası', 'Fransız Güney Bölgeleri', 'Fransız Polinezyası', 'Gabon', 'Gambia',
			  'Gana', 'Gine', 'Gine-Bissau', 'Granada', 'Grönland', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey',
			  'Guyana', 'Güney Afrika', 'Güney Georgia ve Güney Sandwich Adaları', 'Güney Kore',
			  'Güney Kıbrıs Rum Kesimi', 'Gürcistan', 'Haiti', 'Heard Adası ve McDonald Adaları', 'Hindistan',
			  'Hint Okyanusu İngiliz Bölgesi', 'Hollanda', 'Hollanda Antilleri', 'Honduras', 'Hong Kong SAR - Çin',
			  'Hırvatistan', 'Irak', 'İngiliz Virgin Adaları', 'İran', 'İrlanda', 'İspanya', 'İsrail', 'İsveç',
			  'İsviçre', 'İtalya', 'İzlanda', 'Jamaika', 'Japonya', 'Jersey', 'Kamboçya', 'Kamerun', 'Kanada',
			  'Karadağ', 'Katar', 'Kayman Adaları', 'Kazakistan', 'Kenya', 'Kiribati', 'Kolombiya', 'Komorlar',
			  'Kongo', 'Kongo Demokratik Cumhuriyeti', 'Kosta Rika', 'Kuveyt', 'Kuzey Kore', 'Kuzey Mariana Adaları',
			  'Küba', 'Kırgızistan', 'Laos', 'Lesotho', 'Letonya', 'Liberya', 'Libya', 'Liechtenstein', 'Litvanya',
			  'Lübnan', 'Lüksemburg', 'Macaristan', 'Madagaskar', 'Makao S.A.R. Çin', 'Makedonya', 'Malavi',
			  'Maldivler', 'Malezya', 'Mali', 'Malta', 'Man Adası', 'Marshall Adaları', 'Martinik', 'Mauritius',
			  'Mayotte', 'Meksika', 'Mikronezya Federal Eyaletleri', 'Moldovya Cumhuriyeti', 'Monako', 'Montserrat',
			  'Moritanya', 'Mozambik', 'Moğolistan', 'Myanmar', 'Mısır', 'Namibya', 'Nauru', 'Nepal', 'Nijer',
			  'Nijerya', 'Nikaragua', 'Niue', 'Norfolk Adası', 'Norveç', 'Orta Afrika Cumhuriyeti', 'Özbekistan',
			  'Pakistan', 'Palau', 'Panama', 'Papua Yeni Gine', 'Paraguay', 'Peru', 'Pitcairn', 'Polonya',
			  'Portekiz', 'Porto Riko', 'Reunion', 'Romanya', 'Ruanda', 'Rusya Federasyonu', 'Saint Helena',
			  'Saint Kitts ve Nevis', 'Saint Lucia', 'Saint Pierre ve Miquelon', 'Saint Vincent ve Grenadinler',
			  'Samoa', 'San Marino', 'Sao Tome ve Principe', 'Senegal', 'Seyşeller', 'Sierra Leone', 'Singapur',
			  'Slovakya', 'Slovenya', 'Solomon Adaları', 'Somali', 'Sri Lanka', 'Sudan', 'Surinam', 'Suriye',
			  'Suudi Arabistan', 'Svalbard ve Jan Mayen', 'Svaziland', 'Sırbistan', 'Sırbistan-Karadağ', 'Şili',
			  'Tacikistan', 'Tanzanya', 'Tayland', 'Tayvan', 'Togo', 'Tokelau', 'Tonga', 'Trinidad ve Tobago',
			  'Tunus', 'Turks ve Caicos Adaları', 'Tuvalu', 'Türkmenistan', 'Uganda', 'Ukrayna', 'Umman', 'Uruguay',
			  'Uzak Okyanusya', 'Ürdün', 'Vanuatu', 'Vatikan', 'Venezuela', 'Vietnam', 'Wallis ve Futuna', 'Yemen',
			  'Yeni Kaledonya', 'Yeni Zelanda', 'Yunanistan', 'Zambiya', 'Zimbabve']

continents = ["Asya", "Kuzey Amerika", "Güney Amerika", "Amerika", "Afrika", "Antartika", "Okyanusya",  "Avrupa",
			  "Avustralya"]

capitals = ["Andorra la Vell" ,
            "Kabul" ,
            "St. John's" ,
            "Tirana" ,
            "Yerevan" ,
            "Luanda" ,
            "Buenos Aires" ,
            "Vienna" ,
            "Canberra" ,
            "Baku" ,
            "Bridgetown" ,
            "Dhaka" ,
            "Brussels" ,
            "Ouagadougou" ,
            "Sofia" ,
            "Manama" ,
            "Bujumbura" ,
            "Porto-Novo" ,
            "Bandar Seri Beg" ,
            "Sucre" ,
            "Bras" ,
            "Nassau" ,
            "Thimphu" ,
            "Gaborone" ,
            "Minsk" ,
            "Belmopan" ,
            "Ottawa" ,
            "Kinshasa" ,
            "Brazzaville" ,
            "Yamoussoukro" ,
            "Santiago" ,
            "Yaound" ,
            "Beijing" ,
            "Bogot" ,
            "San Jos" ,
            "Havana" ,
            "Praia" ,
            "Nicosia" ,
            "Prague" ,
            "Berlin" ,
            "Djibouti City" ,
            "Copenhagen" ,
            "Roseau" ,
            "Santo Domingo" ,
            "Quito" ,
            "Tallinn" ,
            "Cairo" ,
            "Asmara" ,
            "Addis Ababa" ,
            "Helsinki" ,
            "Suva" ,
            "Paris" ,
            "Libreville" ,
            "Tbilisi" ,
            "Accra" ,
            "Banjul" ,
            "Conakry" ,
            "Athens" ,
            "Guatemala City" ,
            "Port-au-Prince" ,
            "Bissau" ,
            "Georgetown" ,
            "Tegucigalpa" ,
            "Budapest" ,
            "Jakarta" ,
            "Dublin" ,
            "Jerusalem" ,
            "New Delhi" ,
            "Baghdad" ,
            "Tehran" ,
            "Reykjav" ,
            "Rome" ,
            "Kingston" ,
            "Amman" ,
            "Tokyo" ,
            "Nairobi" ,
            "Bishkek" ,
            "Tarawa" ,
            "Pyongyang" ,
            "Seoul" ,
            "Kuwait City" ,
            "Beirut" ,
            "Vaduz" ,
            "Monrovia" ,
            "Maseru" ,
            "Vilnius" ,
            "Luxembourg City" ,
            "Riga" ,
            "Tripoli" ,
            "Antananarivo" ,
            "Majuro" ,
            "Skopje" ,
            "Bamako" ,
            "Naypyidaw" ,
            "Ulaanbaatar" ,
            "Nouakchott" ,
            "Valletta" ,
            "Port Louis" ,
            "MalÃ©" ,
            "Lilongwe" ,
            "Mexico City" ,
            "Kuala Lumpur" ,
            "Maputo" ,
            "Windhoek" ,
            "Niamey" ,
            "Abuja" ,
            "Managua" ,
            "Amsterdam" ,
            "Oslo" ,
            "Kathmandu" ,
            "Yaren" ,
            "Wellington" ,
            "Muscat" ,
            "Panama City" ,
            "Lima" ,
            "Port Moresby" ,
            "Manila" ,
            "Islamabad" ,
            "Warsaw" ,
            "Lisbon" ,
            "Ngerulmud" ,
            "Asunci" ,
            "Doha" ,
            "Bucharest" ,
            "Moscow" ,
            "Kigali" ,
            "Riyadh" ,
            "Honiara" ,
            "Victoria" ,
            "Khartoum" ,
            "Stockholm" ,
            "Singapore" ,
            "Ljubljana" ,
            "Bratislava" ,
            "Freetown" ,
            "San Marino" ,
            "Dakar" ,
            "Mogadishu" ,
            "Paramaribo" ,
            "Damascus" ,
            "Lom" ,
            "Bangkok" ,
            "Dushanbe" ,
            "Ashgabat" ,
            "Tunis" ,
            "Nuku" ,
            "Ankara" ,
            "Port of Spain" ,
            "Funafuti" ,
            "Dodoma" ,
            "Kiev" ,
            "Kampala" ,
            "Washington, D.C" ,
            "Montevideo" ,
            "Tashkent" ,
            "Vatican City" ,
            "Caracas" ,
            "Hanoi" ,
            "Port Vila" ,
            "Sana'a" ,
            "Lusaka" ,
            "Harare" ,
            "Algiers" ,
            "Sarajevo" ,
            "Phnom Penh" ,
            "Bangui" ,
            "N'Djamena" ,
            "Moroni" ,
            "Zagreb" ,
            "Dili" ,
            "San Salvador" ,
            "Malabo" ,
            "St. George's" ,
            "Astana" ,
            "Vientiane" ,
            "Palikir" ,
            "Chi" ,
            "Monaco" ,
            "Podgorica" ,
            "Rabat" ,
            "Basseterre" ,
            "Castries" ,
            "Kingstown" ,
            "Apia" ,
            "Belgrade" ,
            "Pretoria" ,
            "Madrid" ,
            "Sri Jayewardene" ,
            "Mbabane" ,
            "Bern" ,
            "Abu Dhabi" ,
            "London" ,
			"New York",
			"Hollywood",
			"Visconsin",
			"Michigan"
			]


